### ISSUE TITLE
error: non-extern function is variadic

### ISSUE THREAD

**Issue by jpcamara** [katafrakt/zig-ruby#1]
Fun idea! I read the blog post awhile and decided to try out the code. Unfortunately when I go to compile it I get:

```
# rake benchmark
/zig-ruby/ext/zig_rb/src/main.zig:27:1: error: non-extern function is variadic
fn rb_hundred_doors(...) callconv(.C) ruby.VALUE {
^~
```

Did you see anything similar, or is it potentially just an issue since 0.10.1 came out?

**Comment by katafrakt** [comment]
Thanks for reporting. I haven't played with this code in a while, so I don't have an answer from the top of my head. This code was only running on a git version from Zig, perhaps they changed something in the scope in the meantime. I'll try to find some time to investigate.

**Comment by katafrakt** [comment]
Hey @jpcamara, I finally had some time to look into it. Unfortunately, it seems that with the release of Zig 0.11 a lot of things broke in this repo and it's not trivial (for me) to fix. I'll have to read some more about the revamped build system.

I think it might have never worked on 0.10.1 though. At the time of publishing this code I had to use Zig version from git. I'll let you know if I have some results with upgrading.

**Comment by katafrakt** [comment]
I figured it out. Tested only with current master version on Zig, but should work with 0.11 too.

**Comment by jpcamara** [comment]
Nice! I will give this a try this week, thanks!

**Comment by katafrakt** [comment]
let me know if it still does not work
